CREATE SCHEMA
IF
	NOT EXISTS `mu_shop` DEFAULT CHARACTER
	SET utf8;
USE mu_shop;


DROP TABLE IF EXISTS `MU_MEDIA`;
DROP TABLE IF EXISTS `MU_SPU_STAT`;
DROP TABLE IF EXISTS `MU_PRISE`;
DROP TABLE IF EXISTS `MU_SKU_SEPC_RELATION`;
DROP TABLE IF EXISTS `MU_SKU_STAT`;
DROP TABLE IF EXISTS `MU_MANAGERS`;
DROP TABLE IF EXISTS `MU_SKU`;
DROP TABLE IF EXISTS `MU_SPU`;
DROP TABLE IF EXISTS `MU_SPEC_OPTION`;
DROP TABLE IF EXISTS `MU_SPEC`;
DROP TABLE IF EXISTS `MU_SPU_SUB_CATEGORY`;
DROP TABLE IF EXISTS `MU_SPU_CATEGORY`;
DROP TABLE IF EXISTS `MU_SPU_BRAND`;
DROP TABLE IF EXISTS `MU_SPU_DETAIL`;


CREATE TABLE `MU_SPU` (
`PRODUCT_ID` varchar(64) NOT NULL COMMENT '产品ID',
`BRAND_ID` varchar(64) NULL,
`PRODUCT_NAME` varchar(64) NOT NULL,
`PRODUCT_SUB_NAME` varchar(64) NULL,
`PRODUCT_ENA` varchar(64) NOT NULL COMMENT '产品编码',
`PRODUCT_DESC` varchar(512) NULL,
`PRODUCT_DETAIL_ID` varchar(64) NULL,
`PRODUCT_CATEGORY_ID` varchar(64) NULL,
`PRODUCT_SUBCATEGORY_ID` varchar(64) NULL,
`PRODUCT_STATUS` varchar(40) NOT NULL DEFAULT 'draft' COMMENT '产品状态：草稿(draft)->上架(on_sale)->下架(not_on_sale)->不可用(disable)',
`PRODUCT_SALE_TYPE` varchar(40) NOT NULL DEFAULT 'stock' COMMENT '销售类型：按库存销售(stock)、预售(pre_order)、永远可售(always)',
`PRODUCT_ORDER` int NULL,
`PRODUCT_CREATER_ID` varchar(64) NULL,
`PRODUCT_CREATE_TIME` datetime NULL,
`PRODUCT_UPDATER_ID` varchar(64) NULL,
`PRODUCT_UPDATE_TIME` datetime NULL,
PRIMARY KEY (`PRODUCT_ID`),
INDEX product_ena_index ( `PRODUCT_ENA` )
);

CREATE TABLE `MU_SKU` (
`KEEP_ID` varchar(64) NOT NULL,
`PRODUCT_ID` varchar(64) NOT NULL,
`KEEP_ENA` varchar(64) NOT NULL,
`KEEP_ENA_TYPE` varchar(40) NULL DEFAULT 'auto' COMMENT 'ENA 生成方式   auto(自动生成)   manual(人工录入)',
`KEEP_SIZE_WIDTH` decimal(14,2) ZEROFILL NULL,
`KEEP_SIZE_DEPTH` decimal(14,2) ZEROFILL NULL,
`KEEP_SIZE_HEIGHT` decimal(14,2) ZEROFILL NULL,
`KEEP_WEIGHT` decimal(20,4) ZEROFILL NULL,
`KEEP_BUY_PRISE` decimal(14,2) ZEROFILL NULL COMMENT '货品进价',
`KEEP_MARKET_PRISE` decimal(14,2) ZEROFILL NULL COMMENT '货品市场指导价',
`KEEP_STATUS` varchar(64) NULL COMMENT '库存状态   上架(on_sale)、下架(not_on_sale)',
`KEEP_CREATOR_ID` varchar(64) NULL,
`KEEP_CREATE_TIME` datetime NULL,
`KEEP_UPDATER_ID` varchar(64) NULL,
`KEEP_UPDATE_TIME` datetime NULL,
`KEEP_COUNT` int NULL COMMENT '库存数量',
PRIMARY KEY (`KEEP_ID`) 
)
COMMENT = '产品SKU';
CREATE TABLE `MU_MEDIA` (
`MEDIA_ID` varchar(64) NOT NULL,
`PRODUCT_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NULL,
`MEDIA_MAIN_PIC` varchar(1) NOT NULL,
`MEDIA_URL` varchar(512) NOT NULL,
`MEDIA_EXT` varchar(255) NULL,
PRIMARY KEY (`MEDIA_ID`) 
);
CREATE TABLE `MU_SPU_STAT` (
`PRODUCT_ID` varchar(64) NOT NULL,
`STAT_ORDER_COUNT` int ZEROFILL NOT NULL COMMENT '订单数量',
`STAT_PRODUCT_COUNT` int ZEROFILL NOT NULL COMMENT '产品数量',
`STAT_ADD_CART_COUNT` int ZEROFILL NOT NULL,
`STAT_COLLECT_COUNT` int ZEROFILL NOT NULL,
`STAT_COMMENT_COUNT` int ZEROFILL NOT NULL,
`STAT_SCORE` decimal(14,2) ZEROFILL NOT NULL,
PRIMARY KEY (`PRODUCT_ID`) 
);
CREATE TABLE `MU_SPU_BRAND` (
`BRAND_ID` varchar(64) NOT NULL,
`BRAND_NAME` varchar(64) NOT NULL,
`BRAND_ADDRESS` varchar(255) NULL,
`BRAND_EXT` varchar(4000) NULL,
PRIMARY KEY (`BRAND_ID`) 
);
CREATE TABLE `MU_SPU_DETAIL` (
`DETAIL_ID` varchar(64) NOT NULL,
`DETAIL_CONTENT` longtext NOT NULL,
PRIMARY KEY (`DETAIL_ID`) 
);
CREATE TABLE `MU_SPU_CATEGORY` (
`CATEGORY_ID` varchar(64) NOT NULL,
`CATEGROY_NAME` varchar(64) NOT NULL,
`CATEGROY_ORDER` int ZEROFILL NOT NULL,
PRIMARY KEY (`CATEGORY_ID`) 
);
CREATE TABLE `MU_SPU_SUB_CATEGORY` (
`CATEGORY_ID` varchar(64) NOT NULL,
`CATEGROY_NAME` varchar(64) NOT NULL,
`CATEGROY_ORDER` int NOT NULL,
PRIMARY KEY (`CATEGORY_ID`) 
);
CREATE TABLE `MU_PRISE` (
`PRISE_ID` varchar(64) NOT NULL,
`PRODUCT_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NULL,
`PRISE_VALUE` decimal(14,2) NOT NULL,
`PRISE_VALID_TIME` datetime NOT NULL COMMENT '生效时间',
PRIMARY KEY (`PRISE_ID`) 
);
CREATE TABLE `MU_SPEC` (
`SPEC_ID` varchar(64) NOT NULL,
`SPEC_NAME` varchar(64) NOT NULL COMMENT '规格名：如"1.8m 床" ，"风信蓝"',
`SPEC_ORDER` int ZEROFILL NOT NULL,
PRIMARY KEY (`SPEC_ID`) 
);
CREATE TABLE `MU_SPEC_OPTION` (
`OPTION_ID` varchar(64) NOT NULL,
`OPTION_NAME` varchar(64) NOT NULL COMMENT '规格的选项名：如：长度，颜色等等',
`SPEC_ID` varchar(64) NOT NULL,
PRIMARY KEY (`OPTION_ID`) 
);
CREATE TABLE `MU_SKU_SEPC_RELATION` (
`RELATION_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NOT NULL,
`SPEC_OPTION_ID` varchar(64) NOT NULL,
PRIMARY KEY (`RELATION_ID`) 
);
CREATE TABLE `MU_SKU_STAT` (
`RELATION_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NOT NULL,
`SPEC_OPTION_ID` varchar(64) NOT NULL,
PRIMARY KEY (`RELATION_ID`) 
);


CREATE TABLE `MU_MANAGERS` (
`MANAGER_ID` varchar(64) NOT NULL,
`MANAGER_TOKEN` varchar(255) NOT NULL,
`MANAGER_CREATETIME` datetime NOT NULL,
`MANAGER_NICK` varchar(64) NULL,
`MANAGER_AVATAR` varchar(512) NULL,
PRIMARY KEY (`MANAGER_ID`) 
);


ALTER TABLE `MU_SPU` ADD CONSTRAINT `fk_pro_brand` FOREIGN KEY (`BRAND_ID`) REFERENCES `MU_SPU_BRAND` (`BRAND_ID`) ON DELETE NO ACTION ON UPDATE RESTRICT;
ALTER TABLE `MU_SPU` ADD CONSTRAINT `fk_pro_detail` FOREIGN KEY (`PRODUCT_DETAIL_ID`) REFERENCES `MU_SPU_DETAIL` (`DETAIL_ID`) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE `MU_SPU` ADD CONSTRAINT `fk_pro_category` FOREIGN KEY (`PRODUCT_CATEGORY_ID`) REFERENCES `MU_SPU_CATEGORY` (`CATEGORY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `MU_SPU` ADD CONSTRAINT `fk_pro_sub_category` FOREIGN KEY (`PRODUCT_SUBCATEGORY_ID`) REFERENCES `MU_SPU_SUB_CATEGORY` (`CATEGORY_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `MU_SKU` ADD CONSTRAINT `fk_keep_product` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `MU_SPU` (`PRODUCT_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `MU_MEDIA` ADD CONSTRAINT `fk_media_product` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `MU_SPU` (`PRODUCT_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `MU_MEDIA` ADD CONSTRAINT `fk_media_keep` FOREIGN KEY (`KEEP_ID`) REFERENCES `MU_SKU` (`KEEP_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `MU_SPU_STAT` ADD CONSTRAINT `fk_stat_product` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `MU_SPU` (`PRODUCT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `MU_PRISE` ADD CONSTRAINT `fk_prise_product` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `MU_SPU` (`PRODUCT_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `MU_PRISE` ADD CONSTRAINT `fk_prise_keep` FOREIGN KEY (`KEEP_ID`) REFERENCES `MU_SKU` (`KEEP_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `MU_SKU_SEPC_RELATION` ADD CONSTRAINT `fk_ss_relation_keep` FOREIGN KEY (`KEEP_ID`) REFERENCES `MU_SKU` (`KEEP_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `MU_SKU_SEPC_RELATION` ADD CONSTRAINT `fk_ss_relation_sepc_opt` FOREIGN KEY (`SPEC_OPTION_ID`) REFERENCES `MU_SPEC_OPTION` (`OPTION_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `MU_SPEC_OPTION` ADD CONSTRAINT `fk_spec_option_spec` FOREIGN KEY (`SPEC_ID`) REFERENCES `MU_SPEC` (`SPEC_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

