CREATE SCHEMA
IF
	NOT EXISTS `mu_shop` DEFAULT CHARACTER
	SET utf8;
USE mu_shop;


DROP TABLE IF EXISTS `MU_MEDIA`;
DROP TABLE IF EXISTS `MU_SPU_STAT`;
DROP TABLE IF EXISTS `MU_PRISE`;
DROP TABLE IF EXISTS `MU_SKU_SPEC_RELATION`;
DROP TABLE IF EXISTS `MU_SKU_SEPC_RELATION`;
DROP TABLE IF EXISTS `MU_SKU_STAT`;
DROP TABLE IF EXISTS `MU_MANAGERS_AUTHORITY`;
DROP TABLE IF EXISTS `MU_MANAGERS`;
DROP TABLE IF EXISTS `MU_SKU`;
DROP TABLE IF EXISTS `MU_SPU`;
DROP TABLE IF EXISTS `MU_SPEC_OPTION`;
DROP TABLE IF EXISTS `MU_SPU_SUB_CATEGORY`;
DROP TABLE IF EXISTS `MU_SPU_CATEGORY`;
DROP TABLE IF EXISTS `MU_SPU_BRAND`;
DROP TABLE IF EXISTS `MU_SPU_DETAIL`;


CREATE TABLE `MU_SPU` (
`PRODUCT_ID` varchar(64) NOT NULL COMMENT '产品ID',
`BRAND_ID` varchar(64) NULL,
`PRODUCT_NAME` varchar(64) NOT NULL,
`PRODUCT_ENA` varchar(64) NULL COMMENT '产品编码',
`PRODUCT_DESC` varchar(512) NULL,
`PRODUCT_DETAIL_ID` varchar(64) NULL,
`PRODUCT_MAIN_PIC`  varchar(512) NOT NULL,
`PRODUCT_CATEGORY_ID` varchar(64) NULL,
`PRODUCT_SUBCATEGORY_ID` varchar(64) NULL,
`PRODUCT_STATUS` varchar(40) NOT NULL DEFAULT '1' COMMENT '产品状态：不可用(0)->上架(1)->下架(2)->定时上架(3)',
`PRODUCT_SALE_TYPE` varchar(40) NOT NULL DEFAULT '3' COMMENT '销售类型：按库存销售(1)、预售(2)、永远可售(3)',
`PRODUCT_ORDER` int NOT NULL auto_increment unique key,
`PRODUCT_SELL_COUNT` varchar(40) NOT NULL DEFAULT '0' COMMENT '销售数量',
`PRODUCT_CREATOR_ID` varchar(64) NULL,
`PRODUCT_CREATE_TIME` datetime NULL,
`PRODUCT_UPDATER_ID` varchar(64) NULL,
`PRODUCT_UPDATE_TIME` datetime NULL,
PRIMARY KEY (`PRODUCT_ID`),
INDEX product_ena_index ( `PRODUCT_ENA` )
);

CREATE TABLE `MU_SKU` (
`KEEP_ID` varchar(64) NOT NULL,
`PRODUCT_ID` varchar(64) NOT NULL,
`KEEP_ENA` varchar(64) NULL,
`KEEP_ENA_TYPE` varchar(40) NULL COMMENT 'ENA 生成方式   人工录入(1)  自动生成(2)',
`KEEP_SIZE_WIDTH` decimal(14,2) ZEROFILL NULL,
`KEEP_SIZE_DEPTH` decimal(14,2) ZEROFILL NULL,
`KEEP_SIZE_HEIGHT` decimal(14,2) ZEROFILL NULL,
`KEEP_WEIGHT` decimal(20,4) ZEROFILL NULL,
`KEEP_BUY_PRISE` decimal(14,2) ZEROFILL NULL COMMENT '货品进价',
`KEEP_MARKET_PRISE` decimal(14,2) ZEROFILL NULL COMMENT '货品市场指导价',
`KEEP_STATUS` varchar(40) NULL DEFAULT '1' COMMENT '库存状态  下架(0) 上架(1) ',
`KEEP_CREATOR_ID` varchar(64) NULL,
`KEEP_CREATE_TIME` datetime NULL,
`KEEP_UPDATER_ID` varchar(64) NULL,
`KEEP_UPDATE_TIME` datetime NULL,
`KEEP_COUNT` int NULL COMMENT '库存数量',
`KEEP_UNLIMITED_COUNT` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否无限库存 否(0), 是(1)',
`KEEP_SPEC_DESC` varchar(64) NOT NULL,
PRIMARY KEY (`KEEP_ID`) 
)

COMMENT = '产品SKU';

CREATE TABLE `MU_MEDIA` (
`MEDIA_ID` varchar(64) NOT NULL,
`PRODUCT_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NULL,
`MEDIA_MAIN_PIC` varchar(1) NOT NULL,
`MEDIA_URL` varchar(512) NOT NULL,
`MEDIA_EXT` varchar(255) NULL,
PRIMARY KEY (`MEDIA_ID`) 
);

CREATE TABLE `MU_SPU_STAT` (
`PRODUCT_ID` varchar(64) NOT NULL,
`STAT_ORDER_COUNT` int ZEROFILL NOT NULL COMMENT '订单数量',
`STAT_PRODUCT_COUNT` int ZEROFILL NOT NULL COMMENT '产品数量',
`STAT_ADD_CART_COUNT` int ZEROFILL NOT NULL,
`STAT_COLLECT_COUNT` int ZEROFILL NOT NULL,
`STAT_COMMENT_COUNT` int ZEROFILL NOT NULL,
`STAT_SCORE` decimal(14,2) ZEROFILL NOT NULL,
PRIMARY KEY (`PRODUCT_ID`) 
);

CREATE TABLE `MU_SPU_BRAND` (
`BRAND_ID` varchar(64) NOT NULL,
`BRAND_NAME` varchar(64) NOT NULL,
`BRAND_ADDRESS` varchar(255) NULL,
`BRAND_EXT` varchar(4000) NULL,
PRIMARY KEY (`BRAND_ID`) 
);

CREATE TABLE `MU_SPU_DETAIL` (
`DETAIL_ID` varchar(64) NOT NULL,
`DETAIL_CONTENT` longtext NOT NULL,
`DETAIL_VALID` varchar(1) NOT NULL DEFAULT '1',
`DETAIL_CREATE_TIME` datetime NULL,
PRIMARY KEY (`DETAIL_ID`) 
);

CREATE TABLE `MU_SPU_CATEGORY` (
`CATEGORY_ID` varchar(64) NOT NULL,
`CATEGORY_NAME` varchar(64) NOT NULL,
`CATEGORY_ORDER` int ZEROFILL NOT NULL,
`CATEGORY_VALID` varchar(1) NOT NULL DEFAULT '1',
`CATEGORY_CREATE_TIME` datetime NULL,
PRIMARY KEY (`CATEGORY_ID`) 
);

CREATE TABLE `MU_SPU_SUB_CATEGORY` (
`CATEGORY_ID` varchar(64) NOT NULL,
`CATEGROY_NAME` varchar(64) NOT NULL,
`CATEGROY_ORDER` int NOT NULL,
`CATEGORY_VALID` varchar(1) NOT NULL DEFAULT '1',
`CATEGORY_CREATE_TIME` datetime NULL,
PRIMARY KEY (`CATEGORY_ID`) 
);


CREATE TABLE `MU_PRISE` (
`PRISE_ID` varchar(64) NOT NULL,
`PRODUCT_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NOT NULL,
`PRISE_VALUE` decimal(14,2) NOT NULL,
`PRISE_ORIGIN_VALUE` decimal(14,2) NULL,
`PRISE_VALID_TIME` datetime NOT NULL COMMENT '生效时间',
PRIMARY KEY (`PRISE_ID`) 
);

CREATE TABLE `MU_SKU_STAT` (
`RELATION_ID` varchar(64) NOT NULL,
`KEEP_ID` varchar(64) NOT NULL,
`SPEC_OPTION_ID` varchar(64) NOT NULL,
PRIMARY KEY (`RELATION_ID`) 
);


CREATE TABLE `MU_MANAGERS` (
`MANAGER_ID` varchar(64) NOT NULL,
`MANAGER_PWD` varchar(255) NOT NULL,
`MANAGER_CREATETIME` datetime NOT NULL,
`MANAGER_EMAIL` varchar(255) NULL,
`MANAGER_NICK` varchar(64) NULL,
`MANAGER_AVATAR` varchar(512) NULL,
`MANAGER_VALID` varchar(1) NOT NULL DEFAULT '1',
PRIMARY KEY (`MANAGER_ID`),
INDEX managers_email_index ( `MANAGER_EMAIL` )
);


CREATE TABLE `MU_MANAGERS_AUTHORITY` (
`MANAGER_ID` varchar(64) NOT NULL,
`AUTHORITY_READ` varchar(1) NULL,
`AUTHORITY_WRITE` varchar(1) NULL,
`AUTHORITY_DELETE` varchar(512) NULL,
`AUTHORITY_FROM_ID` varchar(64) NULL COMMENT '上级领导',
PRIMARY KEY (`MANAGER_ID`) 
);


INSERT INTO MU_MANAGERS(manager_id, manager_createtime, manager_pwd, manager_nick, manager_avatar, manager_email) VALUES ('fc256850-6bb6-11e8-81b4-29dba3be24a7', '2018-06-05 16:11:29', 'e10adc3949ba59abbe56e057f20f883e', 'admin','http://img2.touxiang.cn/file/20180608/24c3da179e9aee29728403163f18d3f1.jpg','admin@admin.com');
